### ISSUE TITLE
The packaging for this project did not assign a file to the build artifact

### ISSUE THREAD

**Issue by jeffreyang** [mjiderhamn/promote-maven-plugin#6]
I'm getting this error.  

```
[INFO] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy
 (default-cli) on project da-dsa: 
The packaging for this project did not assign a file to the build artifact -> [Help 1]

[INFO] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal 
org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-cli) on project da-dsa: 
The packaging for this project did not assign a file to the build artifact


```

Here's my pom.xml:

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>test.xyzcm</groupId>
    <artifactId>global-settings</artifactId>
    <version>1.5</version>
    <relativePath>../../global-settings/trunk</relativePath>
  </parent>  
  <groupId>test.xyzcm.portal.dsa</groupId>
  <artifactId>da-dsa</artifactId>

  <packaging>ear</packaging>

  <version>1.16-SNAPSHOT</version>
  <name>da-dsa</name>
  <url>http://maven.apache.org</url>

    <dependencies>
    <dependency>
      <groupId>test.xyzcm.portal.dsa</groupId>
      <artifactId>dsa-entity</artifactId>
      <version>1.4</version>
      <scope>compile</scope>
        <exclusions>
            <exclusion>
                <groupId>*</groupId>
                <artifactId>*</artifactId>
            </exclusion>
        </exclusions>
    </dependency>
  </dependencies>  

  <properties>
    <modjsf.version>1.4</modjsf.version>
  </properties>

  <scm>
    <developerConnection>scm:svn:http://svnhost:8080/svn/xyz/jsf/Test/da-dsa/trunk</developerConnection>
  </scm>

  <build>
      <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-ear-plugin</artifactId>
            <configuration>
                <modules>
                    <jarModule>
                        <groupId>test.xyzcm.portal.dsa</groupId>
                        <artifactId>dsa-entity</artifactId>
                        <bundleDir>lib</bundleDir>
                    </jarModule>
                </modules>
                <filtering>true</filtering>
            </configuration>
        </plugin>
        <plugin>
           <groupId>org.apache.maven.plugins</groupId>
           <artifactId>maven-release-plugin</artifactId>
           <version>2.5.3</version>
            <configuration>
                <completionGoals>promote:artifacts deploy:deploy</completionGoals>
            </configuration>           
        </plugin>
        <plugin>
            <groupId>se.jiderhamn</groupId>
            <artifactId>promote-maven-plugin</artifactId>
            <version>1.0.2</version>
        </plugin>   

    </plugins>
  </build>    
</project>

```

**Comment by mjiderhamn** [comment]
What command/goals did you run? Considering you did not add `make-promotable` goal to your `pom.xml` as per the [readme](https://github.com/mjiderhamn/promote-maven-plugin), did you run `promote:make-promotable` explicitly?

**Comment by jeffreyang** [comment]
I ran release:clean promote:prepare release:prepare. Yes, I manually ran promote:make-promotable prior.

**Comment by mjiderhamn** [comment]
What does the contents of `promotable-artifacts.properties` look like after your SNAPSHOT build? Are there any errors output by Maven at that time?

**Comment by jeffreyang** [comment]
There are no errors during the generation of promotable-artifacts.properties.  Here's the content:

```

#Generated by promote-maven-plugin
#Tue Jul 26 18:43:02 EDT 2016
artifact.id=test.xyzcm.portal.dsa\:da-dsa\:ear\:1.15-SNAPSHOT
artifact.version=1.15-SNAPSHOT
artifact.groupId=test.xyzcm.portal.dsa
artifact.artifactId=da-dsa
artifact.baseVersion=1.15-SNAPSHOT
artifact.type=ear

```

Note that the artifact versions in pom.xml and here differ.  The pom.xml version already incremented to next development version - 1.16-SNAPSHOT.

**Comment by mjiderhamn** [comment]
What is the name of the .ear file on disk? 1.15-SNAPSHOT or 1.16-SNAPSHOT?

Could you try without the `<completionGoals>` in your pom?

Also, is there any other error or warning in the output before `The packaging for this project did not assign a file to the build artifact`?

**Comment by jeffreyang** [comment]
1.    ear file name in target is da-dsa-1.15-SNAPSHOT.ear 
2.    I get the same error without the completionGoals
3.   I see an error before:  `[ERROR] No file registered for artifact: test.xyzcm.portal.dsa:da-dsa:ear:1.15-SNAPSHOT`

Note that if packaging is jar, i can make it work by adding jar:jar, like so:  `<completionGoals>promote:artifacts jar:jar deploy:deploy</completionGoals>`

**Comment by jeffreyang** [comment]
Hi, I'm just wondering if this is an easy fix, or if it'll take some time?

**Comment by mjiderhamn** [comment]
I don't have enough experience with EARs to know if Maven does something differently. Unfortunately it will probably be a week or two before I can find the time to investigate.

**Comment by mjiderhamn** [comment]
I am unable to recreate this issue. I have a test project [here](https://github.com/mjiderhamn/promote-ear) that (after adding `<distributionManagement>`) releases just fine with the plugin.

Can you create a minimized project that demonstrates your problem?

**Comment by mjiderhamn** [comment]
Closing due to lack of response from reporter
