### ISSUE TITLE
Usage question

### ISSUE THREAD

**Issue by marklagendijk** [mjiderhamn/promote-maven-plugin#8]
I am looking for a way to do only a deploy with Maven.
My current flow is this:

1. Set the release version. E.g. `7.1.2`. Done via a custom script, because the mvn version command is too slow.
2. Compile the software: `mvn clean install -DskipTests -DskipITs -T C1`
3. Run the unit tests: `mvn surefire:test -Djavax.xml.accessExternalSchema=all -Djavax.xml.accessExternalDTD=all -DskipITs -T C1`
4. Run the integration tests: `mvn -Djavax.xml.accessExternalSchema=all -Djavax.xml.accessExternalDTD=all -DonlyITs`
5. Deploy the software to Nexus (OSS): `mvn deploy -DskipTests -DskipITs -Dmaven.validate.skip=true -Dmaven.compile.skip=true -Dmaven.test.skip=true -Dmaven.package.skip=true -Dmaven.integration-test.skip=true -Dmaven.verify.skip=true -T 1C`

Can I use this plugin with this flow?
My understanding is that I could use it as follows.
Step 1: `mvn clean install promote:make-promotable -DskipTests -DskipITs -T C1`
Step 5:  `mvn promote:artifacts deploy:deploy  -T 1C`.
The effect of this would then be that step 5 only uploads the artifacts to Nexus, and does not execute any other steps.
Is this correct?

**Comment by mjiderhamn** [comment]
Hi Mark. Sorry for the late reply.

What does your VCS setup look like? Do you want to do any tagging as part of the release?

When using `promote:prepare release:prepare` it basically does three things

- Change the version in the POMs
- Commit the POMs and tag the commit
- `deploy:deploy`

If you don't want to involve VCS in your release, I'm not sure there is much benefit for you using this plugin compared to what you do now. If you do want to update the VCS however, I encourage you to give the plugin a try.
