### ISSUE TITLE
promotion version question

### ISSUE THREAD

**Issue by bnagirner** [mjiderhamn/promote-maven-plugin#9]
I have a zip assembly that is made up of a project jar.  Both the zip file and the the project jar it contains need to have the same version.  

During a snapshot build both contain the correct snapshot version.
However, when running the mvn promote plugin the zip file is updated correctly with the release version but the project jar inside it still contain -SNAPSHOT in  the version.  This is the promote command that I run:

    --settings  ${WORKSPACE}/../../settings.xml -B release:clean promote:prepare -Dtag=${PROMOTED_PRODUCTION_VERSION} release:prepare  -DreleaseVersion=${PROMOTED_MVN_VERSION} -DdevelopmentVersion=${PROMOTED_MVN_DEVELOPMENT_VERSION}

In my pom file:

      <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-assembly-plugin</artifactId>
          <version>2.6</version>
          <executions>
            <execution>
                <id>jar-with-dependencies</id>
                <phase>package</phase>
                <goals>
                  <goal>single</goal>
                </goals>
                <configuration>
                  <finalName>${finalName}</finalName>
                  <descriptorRefs>
                    <descriptorRef>jar-with-dependencies</descriptorRef>
                  </descriptorRefs>
                  <archive>
                    <manifest>
                      <addDefaultImplementationEntries>true</addDefaultImplementationEntries>
                      <addDefaultSpecificationEntries>true</addDefaultSpecificationEntries>
                      <mainClass>${mainClass}</mainClass>
                    </manifest>
                  </archive>
                  <appendAssemblyId>false</appendAssemblyId>
                </configuration>
            </execution>
            <execution>
                <id>distribution</id>
                <phase>package</phase>
                <goals>
                    <goal>single</goal>
                </goals>
                <configuration>
                    <finalName>${finalName}</finalName>
                    <filters>
                        <filter>src/main/assembly/filter.properties</filter>
                    </filters>
                    <descriptors>
                        <descriptor>src/main/assembly/distribution.xml</descriptor>
                    </descriptors>
                </configuration>
            </execution>
          </executions>
      </plugin>

The assembly file:

    <assembly xmlns="http://maven.apache.org/ASSEMBLY/2.0.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/ASSEMBLY/2.0.0 http://maven.apache.org/xsd/assembly-2.0.0.xsd">
      <id>distribution</id>
      <formats>
        <format>zip</format>
      </formats>
      <includeBaseDirectory>false</includeBaseDirectory>
    
      <files>
        <file>
          <source>Dockerfile</source>
          <outputDirectory></outputDirectory>
          <filtered>true</filtered>
        </file>
        <file>
          <source>Dockerrun.aws.json</source>
          <outputDirectory></outputDirectory>
        </file>
        <file>
          <source>
            target/${finalName}.jar
          </source>
          <outputDirectory>target</outputDirectory>
        </file>
      </files>
    </assembly>

The resulting promoted zip is: **name-1.0.0.0.zip** and it contains a jar **name-1.0.0.0-SNAPSHOT.jar**.  The jar **name-1.0.0.0.jar** is created and deployed to artifactory.  How can I also make sure **name-1.0.0.0.jar** is contained within the assembly as well?

The contents of promotable-artifacts.properties (note that due to the CI setup I am overriding the version in the pom file with a new version that is passed to the build.)

`#Generated by promote-maven-plugin
#Tue Jun 06 11:46:27 CDT 2017
attached.0.classifier=distribution
artifact.id=com.lifesize\:cloud.service.callhistory\:jar\:1.0.1.0-SNAPSHOT
artifact.baseVersion=1.0.1.0-SNAPSHOT
attached.0.id=com.lifesize\:cloud.service.callhistory\:zip\:distribution\:1.0.1.0-SNAPSHOT
attached.0.baseVersion=1.0.1.0-SNAPSHOT
attached.0.artifactId=cloud.service.callhistory
artifact.type=jar
artifact.groupId=com.lifesize
attached.0.type=zip
attached.0.groupId=com.lifesize
artifact.version=1.0.1.0-SNAPSHOT
artifact.artifactId=cloud.service.callhistory
attached.0.version=1.0.1.0-SNAPSHOT
artifact.file=release_1.0.0.0-SNAPSHOT_Callhistory-63.jar
attached.0.file=release_1.0.0.0-SNAPSHOT_Callhistory-63-distribution.zip`

Thanks

**Comment by mjiderhamn** [comment]
Hi @bnagirner . As [mentioned in the readme](https://github.com/mjiderhamn/promote-maven-plugin#caveat), this plugin will not rename artifacts "nested" inside other artifacts during promotion. At this point I have no intention of adding support for that, since it is outside the scope of the plugin. (If you however choose to add that as an option, feel free to send me a Pull request!).

With the plugin as it is, you could either choose not to use it, or - if possible - create the ZIP after promoting the JAR.
